In [4]:
import numpy as np
import pandas as pd

1.	Write a Python Program to Add Two Matrices?

In [28]:
a = np.random.randint(20,70,20).reshape(5,4) #here we created matrix from random number of 5 x 4 

b = np.random.randint(20,70,20).reshape(5,4) # #here we created matrix from random number of 5 x 4 

print(f'addition of two matrix is {a+b}')

addition of two matrix is [[116 112  51  54]
 [106  88  51  99]
 [ 99  71 125 122]
 [ 88  67  79  52]
 [ 77  74 130 101]]


2.	Write a Python Program to Multiply Two Matrices?

In [38]:
a = np.random.randint(1,70,20).reshape(5,4)
b = np.random.randint(1,70,20).reshape(5,4)

print(f'multiplication of two matrix is {a*b}')

multiplication of two matrix is [[ 129 2709 1517 1040]
 [3599  775  455  102]
 [1534 1890  234  795]
 [1920 1734 1088  483]
 [ 702 1935 1824  128]]


3.	Write a Python Program to Transpose a Matrix?

In [47]:
li = [1,2,3,4,5,6]
a = np.array(li).reshape(2,3)
print(f'2-D matrix is :  {a}')

b = a.T
print(f'Transpose of 2-D matrix is : {b}')

2-D matrix is :  [[1 2 3]
 [4 5 6]]
Transpose of 2-D matrix is : [[1 4]
 [2 5]
 [3 6]]


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [5]:
sentence = "Write a Python Program to Sort Words in Alphabetic Order"

# Split the sentence into words
words = sentence.split()
print(words)

# Sort the words
words.sort()

# Join the sorted words back into a sentence
sorted_sentence = ' '.join(words)

print(sorted_sentence)

['Write', 'a', 'Python', 'Program', 'to', 'Sort', 'Words', 'in', 'Alphabetic', 'Order']
Alphabetic Order Program Python Sort Words Write a in to


5.	Write a Python Program to Remove Punctuation From a String?

In [6]:
# Import the string library
import string

s = "Hello, World!! This is a Python program."

# Create a translation table that maps every punctuation to None
translator = str.maketrans('', '', string.punctuation)

# Use the translation table to remove all punctuation from the string
s_without_punctuation = s.translate(translator)

print(s_without_punctuation)

Hello World This is a Python program
